spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  application:
    name: user-service


auth:
  token:
    jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D

idp:
    url: http://localhost:8081
    client:
        id: ecommerce_ms_app
        realm: springboot-ms-realm
        secret: B9HnviniWRfOQEKzEhLROtl3USI13Irl
        grant-type: client_credentials
        scope: openid
    admin:
        username: admin
        password: admin