spring:
  config:
#      import: optional:configserver:http://config-service:8888
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  application:
    name: discovery-service


