services:
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql-e-commerce
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3307:3306"
    volumes:
        - e-commerce-mysql-data:/var/lib/mysql
    networks:
        - e-commerce-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - e-commerce-network


volumes:
    e-commerce-mysql-data:

networks:
    e-commerce-network:
        driver: bridge