spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
  application:
    name: auth-service


  auth:
    token:
      expirationInMils: 600000
      refreshExpirationInMils: 3600000
      jwtSecret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D

