package com.nhattung.enums;

public enum OrderStatus {
    ORDER_CREATED,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    INVENTORY_PROCESSING,
    INVENTORY_CHECKED,
    INVENTORY_COMPLETED,
    INVENTORY_FAILED,
    DELIVERY_PROCESSING,
    DELIVERY_COMPLETED,
    DELIVERY_FAILED,
    ORDER_COMPLETED,
    ORDER_CANCELLED
}
