
app:
  apiPrefix: /api/v1

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=${app.apiPrefix}/auth/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.apiPrefix}/user-profile/**
          filters:
            - StripPrefix=2
server:
  port: 8080

