
app:
  apiPrefix: /api/v1

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=${app.apiPrefix}/auth/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.apiPrefix}/user-profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.apiPrefix}/notification/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/springboot-ms-realm
        registration:
          keycloak-client:
            client-id: ecommerce_ms_app
            client-secret: B9HnviniWRfOQEKzEhLROtl3USI13Irl
            authorization-grant-type: client_credentials
            scope: openid


server:
  port: 8080

