eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
name:
  value: nhattung


management:
  tracing:
    sampling:
      probability: 1.0