spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ms_auth_db
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090

#openfeign
feign:
  client:
    config:
      default:
        connectTimeout: 5000 # thời gian bắt đầu gọi đến khi kết nối
        readTimeout: 5000   # thời gian đọc dữ liệu từ server
  circuitbreaker: # cho phép fallback
    enabled: true

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s # thời gian timeout
