spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm
server:
  port: 8090

idp:
  url: http://localhost:8081/realms/springboot-ms-realm/protocol/openid-connect
  client:
    id: ecommerce_ms_app
    realm: springboot-ms-realm
    secret: B9HnviniWRfOQEKzEhLROtl3USI13Irl
    grant-type: password
    scope: openid
  frontendUrl: http://localhost:5173