spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm
#          issuer-uri: http://keycloak-ms:8080/realms/springboot-ms-realm
  redis:
    host: localhost
#    host: redis
    port: 6379
  cache:
    type: redis

server:
  port: 8100


gemini:
  url: https://generativelanguage.googleapis.com/v1beta
  api-key: AIzaSyDKvm0-8FOy_bPNvRnXbUyM8w9yFHJVolM




