spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm


server:
  port: 8100


gemini:
  url: https://generativelanguage.googleapis.com/v1beta
  api-key: AIzaSyDKvm0-8FOy_bPNvRnXbUyM8w9yFHJVolM




