spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ms_product_db
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis

server:
  port: 8093



aws:
  s3:
    bucketName: springboot-ms-product-bucket
  region: ap-southeast-1
  accessKey: AKIAYDWHTGML7NBSMHOB
  secretKey: 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