spring:
  datasource:
    url: jdbc:mysql://localhost:3307/ms_user_db
#    url: jdbc:mysql://mysql-e-commerce:3306/ms_user_db
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9094
#    bootstrap-servers: kafka:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-ms-realm
#          issuer-uri: http://localhost:8080/realms/springboot-ms-realm
  redis:
    host: localhost
#    host: redis
    port: 6379
  cache:
    type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


server:
  port: 8091

idp:
  url: http://localhost:8081
#  url: http://keycloak-ms:8080
  client:
    id: ecommerce_ms_app
    realm: springboot-ms-realm
    secret: B9HnviniWRfOQEKzEhLROtl3USI13Irl
    grant-type: client_credentials
    scope: openid
  admin:
    username: admin
    password: admin

aws:
  s3:
    bucketName: springboot-ms-product-bucket
  region: ap-southeast-1
  accessKey: AKIAYDWHTGML7NBSMHOB
  secretKey: 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
##openfeign
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000 # thời gian bắt đầu gọi đến khi kết nối
#        readTimeout: 5000   # thời gian đọc dữ liệu từ server
#  circuitbreaker: # cho phép fallback
#    enabled: true
#
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeoutDuration: 5s # thời gian timeout